# Generated by Django 4.2.3 on 2023-09-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlexieApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexieusers',
            name='username',
        ),
        migrations.AddField(
            model_name='flexieusers',
            name='upload_file',
            field=models.FileField(null=True, upload_to='uploads/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='flexieusers',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='flexieusers',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name=''),
        ),
    ]
