# Generated by Django 4.2.3 on 2023-09-07 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlexieApp', '0002_remove_flexieusers_username_flexieusers_upload_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexieusers',
            name='uploaded_at',
        ),
    ]
